export const genres = [
  "Young Adult",
  "Fiction",
  "Dystopia",
  "Fantasy",
  "Science Fiction",
  "Romance",
  "Adventure",
  "Teen",
  "Post Apocalyptic",
  "Action",
  "Magic",
  "Childrens",
  "Audiobook",
  "Middle Grade",
  "Classics",
  "Science Fiction Fantasy",
  "Historical Fiction",
  "School",
  "Literature",
  "Historical",
  "Novels",
  "Read For School",
  "High School",
  "Historical Romance",
  "Classic Literature",
  "Adult",
  "Vampires",
  "Paranormal",
  "Paranormal Romance",
  "Supernatural",
  "Urban Fantasy",
  "War",
  "Holocaust",
  "World War II",
  "Books About Books",
  "Politics",
  "Christian",
  "Christian Fiction",
  "Epic Fantasy",
  "High Fantasy",
  "Civil War",
  "Contemporary",
  "Realistic Fiction",
  "Coming Of Age",
  "Drama",
  "Love",
  "Humor",
  "Comedy",
  "Picture Books",
  "Poetry",
  "Juvenile",
  "Kids",
  "Short Stories",
  "Gothic",
  "19th Century",
  "Mystery",
  "Thriller",
  "Suspense",
  "Mystery Thriller",
  "Crime",
  "Japan",
  "Asia",
  "Adult Fiction",
  "Horror",
  "LGBT",
  "British Literature",
  "France",
  "French Literature",
  "Plays",
  "Philosophy",
  "Spirituality",
  "Self Help",
  "Inspirational",
  "Russia",
  "Russian Literature",
  "Mental Health",
  "American",
  "Angels",
  "Chick Lit",
  "Book Club",
  "Canada",
  "Animals",
  "Chapter Books",
  "Time Travel",
  "Magical Realism",
  "Spanish Literature",
  "Literary Fiction",
  "Latin American",
  "Fairy Tales",
  "Mythology",
  "Greek Mythology",
  "Dragons",
  "Epic",
  "Monsters",
  "Food",
  "India",
  "20th Century",
  "Feminism",
  "Unfinished",
  "Space Opera",
  "Medieval",
  "Apocalyptic",
  "Detective",
  "Victorian",
  "Psychology",
  "Mental Illness",
  "Scotland",
  "Family",
  "Sweden",
  "African American",
  "New York",
  "Modern Classics",
  "Religion",
  "Nonfiction",
  "Memoir",
  "Biography",
  "Ireland",
  "Autobiography",
  "Biography Memoir",
  "History",
  "Irish Literature",
  "Buddhism",
  "German Literature",
  "Africa",
  "Steampunk",
  "Spain",
  "Economics",
  "Contemporary Romance",
  "Womens",
  "Queer",
  "Young Adult Fantasy",
  "Travel",
  "Young Adult Contemporary",
  "Counting",
  "Storytime",
  "Mathematics",
  "Czech Literature",
  "Italian Literature",
  "Italy",
  "True Crime",
  "Cats",
  "Westerns",
  "Graphic Novels",
  "Comics",
  "Graphic Novels Comics",
  "Comic Book",
  "Superheroes",
  "World War I",
  "Theatre",
  "Australia",
  "Christmas",
  "Holiday",
  "Environment",
  "China",
  "Arthurian",
  "Banned Books",
  "Pirates",
  "Erotica",
  "BDSM",
  "Erotic Romance",
  "Prehistoric",
  "Retellings",
  "Witches",
  "Japanese Literature",
  "Tudor Period",
  "Media Tie In",
  "Dinosaurs",
  "Biblical Fiction",
  "Biblical",
  "New Adult",
  "Indian Literature",
  "Christianity",
  "Theology",
  "Faith",
  "Art",
  "Werewolves",
  "Dogs",
  "Portugal",
  "Portuguese Literature",
  "Southern Gothic",
  "Southern",
  "Journalism",
  "Comic Strips",
  "Race",
  "Speculative Fiction",
  "Survival",
  "College",
  "Tragedy",
  "Egypt",
  "Ancient History",
  "Abuse",
  "Nature",
  "18th Century",
  "Travelogue",
  "Reference",
  "Space",
  "Military Fiction",
  "Anthologies",
  "Childrens Classics",
  "Scandinavian Literature",
  "Essays",
  "Cyberpunk",
  "Fae",
  "African Literature",
  "Nigeria",
  "English Literature",
  "South Africa",
  "Legal Thriller",
  "Science",
  "Popular Science",
  "Physics",
  "Music",
  "Death",
  "Horses",
  "Ghosts",
  "Regency",
  "Germany",
  "Jewish",
  "True Story",
  "Taoism",
  "Eastern Philosophy",
  "Aliens",
  "Law",
  "Biology",
  "Evolution",
  "Anthropology",
  "Political Science",
  "Asian Literature",
  "Young Adult Romance",
  "Futuristic",
  "French Revolution",
  "Alternate History",
  "Judaism",
  "Swedish Literature",
  "American History",
  "Christian Romance",
  "Robots",
  "Ancient",
  "Dark",
  "Fairies",
  "Folklore",
  "Atheism",
  "Zombies",
  "Education",
  "Pakistan",
  "The United States Of America",
  "Demons",
  "Mountaineering",
  "Sports",
  "Medicine",
  "Ethiopia",
  "Medical",
  "Theory",
  "Academic",
  "Unicorns",
  "Business",
  "Leadership",
  "Personal Development",
  "New Age",
  "Horse Racing",
  "American Civil War",
  "Espionage",
  "Social Justice",
  "Astronomy",
  "Presidents",
  "American Revolution",
  "Gender",
  "Greece",
  "Nobel Prize",
  "Noir",
  "Native Americans",
  "Writing",
  "Botswana",
  "Love Story",
  "Road Trip",
  "Sociology",
  "Finance",
  "Social Science",
  "Health",
  "Nutrition",
  "Cooking",
  "Disability",
  "Halloween",
  "Communication",
  "Relationships",
  "Aviation",
  "Romanticism",
  "Collections",
  "Israel",
  "European History",
  "Productivity",
  "Management",
  "Fighters",
  "Psychological Thriller",
  "Liberia",
  "Sierra Leone",
  "Art History",
  "Beauty and The Beast",
  "Fairy Tale Retellings",
  "Outdoors",
  "Roman",
  "Murder Mystery",
  "Shapeshifters",
  "Marriage",
  "Architecture",
  "Hinduism",
  "Animal Fiction",
  "Gay",
  "M M Romance",
  "Novella",
  "Brazil",
  "Denmark",
  "Danish",
  "Fashion",
  "Computer Science",
  "Lesbian",
  "Cults",
  "Latin American Literature",
  "Weird Fiction",
  "Lovecraftian",
  "Cultural",
  "Dark Fantasy",
  "Canadian Literature",
  "Turkish Literature",
  "Turkish",
  "Iran",
  "Wolves",
  "14th Century",
  "Historical Mystery",
  "Batman",
  "Dc Comics",
  "Americana",
  "Genetics",
  "Romantic Suspense",
  "Emotion",
  "Polish Literature",
  "Womens Fiction",
  "New Weird",
  "Hugo Awards",
  "Sudan",
  "Diary",
  "Poland",
  "Buisness",
  "Sports Romance",
  "Christian Non Fiction",
  "Money",
  "Personal Finance",
  "Entrepreneurship",
  "Baseball",
  "Young Adult Paranormal",
  "Spy Thriller",
  "Elves",
  "15th Century",
  "Plantagenet",
  "Skepticism",
  "Police",
  "Catholic",
  "Archaeology",
  "Christian Living",
  "Gardening",
  "Historical Fantasy",
  "Conspiracy Theories",
  "Occult",
  "Medieval History",
  "World History",
  "Military History",
  "Ecology",
  "Sustainability",
  "Technology",
  "Gaming",
  "Games",
  "Game Design",
  "Ukraine",
  "Utopia",
  "Kenya",
  "Language",
  "Linguistics",
  "Rabbits",
  "Serbian Literature",
  "Manga",
  "Comic Fantasy",
  "Ghost Stories",
  "Amazon",
  "Finnish Literature",
  "Poverty",
  "Social Issues",
  "Parenting",
  "Hard Boiled",
  "Christian Fantasy",
  "Aspergers",
  "Somalia",
  "Nordic Noir",
  "Gender Studies",
  "Wildlife",
  "Anime",
  "Shojo",
  "Comics Manga",
  "Counter Culture",
  "Illness",
  "Time Travel Romance",
  "Lds",
  "Church",
  "Lds Non Fiction",
  "Young Adult Historical Fiction",
  "Cartoon",
  "Dutch Literature",
  "Artificial Intelligence",
  "16th Century",
  "American Revolutionary War",
  "Islam",
  "Heroic Fantasy",
  "Sword and Sorcery",
  "Forgotten Realms",
  "Dungeons and Dragons",
  "Dragonlance",
  "Regency Romance",
  "Amish",
  "Geography",
  "Christian Historical Fiction",
  "Doctors",
  "Chess",
  "Martial Arts",
  "Engineering",
  "Pop Culture",
  "Morocco",
  "Pulp",
  "Wizards",
  "Comix",
  "Adoption",
  "Modern",
  "Hockey",
  "Teaching",
  "Boarding School",
  "Star Wars",
  "Cult Classics",
  "Clean Romance",
  "Fitness",
  "Metaphysics",
  "Fantasy Romance",
  "17th Century",
  "Natural History",
  "Fan Fiction",
  "Mermaids",
  "Society",
  "Mormonism",
  "Neuroscience",
  "Poetry Plays",
  "Discipleship",
  "21st Century",
  "Menage",
  "Musicians",
  "13th Century",
  "Mixed Martial Arts",
  "Short Story Collection",
  "M F Romance",
  "Walking",
  "Lebanon",
  "Egyptian Literature",
  "Young Adult Science Fiction",
  "Science Fiction Romance",
  "Gods",
  "Rock N Roll",
  "Mysticism",
  "Psychoanalysis",
  "Hard Science Fiction",
  "Ghana",
  "Health Care",
  "Foodie",
  "Activism",
  "Urban",
  "Academia",
  "Dying Earth",
  "Fostering",
  "Rwanda",
  "Anarchism",
  "Satanism",
  "Transgender",
  "Design",
  "12th Century",
  "Chinese Literature",
  "Sexuality",
  "Lds Fiction",
  "Belgium",
  "Film",
  "Medieval Romance",
  "Romantic",
  "Plants",
  "Zimbabwe",
  "Anti Racist",
  "Western Romance",
  "Hungarian Literature",
  "Hungary",
  "Drawing",
  "How To",
  "Art Design",
  "Research",
  "Anglo Saxon",
  "Video Games",
  "Motorcycle",
  "Shonen",
  "Maritime",
  "Anthropomorphic",
  "Military Science Fiction",
  "Logic",
  "American Fiction",
  "Cities",
  "Urban Planning",
  "Vegan",
  "Cozy Mystery",
  "Deception",
  "Princesses",
  "United States",
  "Bulgaria",
  "Bulgarian Literature",
  "Textbooks",
  "Technical",
  "Virtual Reality",
  "Prayer",
  "Photography",
  "Criticism",
  "Harlequin Teen",
  "Indonesian Literature",
  "Banks",
  "Sequential Art",
  "Reverse Harem",
  "Cycling",
  "Russian History",
  "Guides",
  "Own",
  "M F M",
  "Superman",
  "Fandom",
  "Wicca",
  "Bande Dessinée",
  "Josei",
  "Music Biography",
  "Queer Lit",
  "The World",
  "Programming",
  "Native American History",
  "Love Inspired",
  "Love Inspired Historical",
  "Literary Criticism",
  "Journal",
  "Georgian",
  "Young Readers",
  "Brain",
  "Lesbian Fiction",
  "Military Romance",
  "Knitting",
  "European Literature",
  "Cinderella",
  "Sao Tome and Principe",
  "Prostitution",
  "Divorce",
  "Social",
  "Geek",
  "Computers",
  "Birds",
  "Epic Poetry",
  "Swashbuckling",
  "Transport",
  "Government",
  "New Adult Romance",
  "God",
  "Football",
  "History Of Science",
  "Counselling",
  "Romanian Literature",
  "Romania",
  "Cthulhu Mythos",
  "Dictionaries",
  "Journaling",
  "Crafts",
  "Prehistory",
  "Spanish Civil War",
  "Wilderness",
  "Number",
  "International",
  "Surreal",
  "Us Presidents",
  "Naval History",
  "Cameroon",
  "Light Novel",
  "Street Art",
  "Graffiti",
  "Terrorism",
  "Seinen",
  "Kazakhstan",
  "Classical Studies",
  "Futurism",
  "Polygamy",
  "Singularity",
  "Gay For You",
  "Quantum Mechanics",
  "Cookbooks",
  "Fat Acceptance",
  "Fat",
  "Fat Studies",
  "Womens Studies",
  "Geometry",
  "Scripture",
  "Gothic Romance",
  "Tasmania",
  "Humanities",
  "Basketball",
  "Recreation",
  "Female Authors",
  "Marvel",
  "Social Work",
  "Psychiatry",
  "X Men",
  "Fables",
  "Harlequin",
  "Hackers",
  "Microhistory",
  "Elizabethan Period",
  "Bolivia",
  "Teachers",
  "African American Literature",
  "Climbing",
  "Soccer",
  "Sci Fi Fantasy",
  "Paranormal Mystery",
  "Class",
  "Judaica",
  "Culinary",
  "Food and Drink",
  "Zen",
  "Punk",
  "Oral History",
  "Lesbian Romance",
  "Holland",
  "Gay Fiction",
  "Splatterpunk",
  "Interracial Romance",
  "Albanian Literature",
  "Internet",
  "Urbanism",
  "Urban Studies",
  "Jazz",
  "Paganism",
  "Church History",
  "Victor Frankenstein",
  "Slice Of Life",
  "Near Future",
  "M M F",
  "Old Testament",
  "Chemistry",
  "M M Fantasy",
  "Nursery Rhymes",
  "Thelema",
  "Magick",
  "Esoterica",
  "Trains",
  "Puzzles",
  "Hip Hop",
  "History and Politics",
  "Alternate Universe",
  "Diets",
  "Climate Change",
  "Bangladesh",
  "Algeria",
  "Palaeontology",
  "Sword and Planet",
  "Science Nature",
  "Social Media",
  "Tea",
  "Art and Photography",
  "Visual Art",
  "Western Historical Romance",
  "Burundi",
  "American Classics",
  "Semiotics",
  "Firefighters",
  "Plus Size",
  "Folk Tales",
  "Geology",
  "Banking",
  "Malawi",
  "Romanovs",
  "2nd Grade",
  "Divination",
  "Drinking",
  "Comedian",
  "Food Writing",
  "Polyamory",
  "Bizarro Fiction",
  "Pre K",
  "Climate Change Fiction",
  "Disease",
  "Post Colonial",
  "Polyamorous",
  "Harlequin Heartwarming",
  "Asexual",
  "Wine",
  "Baha I",
  "Software",
  "Coding",
  "Graphic Novels Manga",
  "Usability",
  "Website Design",
  "African American Romance",
  "40k",
  "Warcraft",
  "World Of Warcraft",
  "Togo",
  "Nerd",
  "Soviet History",
  "Russian Revolution",
  "1st Grade",
  "Soldiers",
  "Musicals",
  "Labor",
  "Doctor Who",
  "Belgian",
  "Feminist Theory",
  "Mozambique",
  "School Stories",
  "Fire Services",
  "Emergency Services",
  "Buses",
  "Webcomic",
  "Tv",
  "New Testament",
  "Paranormal Urban Fantasy",
  "Slash Fiction",
  "Yeti",
  "Roman Britain",
  "Category Romance",
  "Buffy The Vampire Slayer",
  "Genderqueer",
  "Amish Fiction",
  "Komik",
  "Lenin",
  "International Development",
  "Pilots",
  "International Relations",
  "M M M",
  "Star Trek",
  "Alchemy",
  "Fractured Fairy Tales",
  "Edwardian",
  "Role Playing Games",
  "Growth Mindset",
  "Mary Shelley",
  "Intersex",
  "Weird West",
  "Marathi",
  "Erotic Historical Romance",
  "Planets",
  "Witchcraft",
  "Planetary Romance",
  "Alcohol",
  "Bisexual",
  "Quilting",
  "Mali",
  "Ukrainian Literature",
  "Spider Man",
  "Erotic Horror",
  "Vegetarian",
  "Cryptozoology",
  "Trivia",
  "Victorian Romance",
  "Harem",
  "Ethnography",
  "Eritrea",
  "Google",
  "Cultural Studies",
  "International Literature",
  "Frugal",
  "Grad School",
  "Pornography",
  "Sex Work",
  "Loveswept",
  "Alternative Medicine",
  "Food History",
  "Numerology",
  "Supernatural Romance",
  "Cocktails",
  "Booze",
  "Strippers",
  "Harlequin Romance",
  "Museums",
  "Museology",
  "Agriculture",
  "Horticulture",
  "Battle Of Gettysburg",
  "Evangelism",
  "Lie",
  "Golden Age Mystery",
  "Sewing",
  "Social Movements",
  "NSFW",
  "Mills and Boon",
  "Yaoi",
  "Boys Love",
  "Shounen Ai",
  "Ecclesiology",
  "M M Contemporary",
  "Astrology",
  "Students",
  "Gay Erotica",
  "Intelligent Design",
  "Conservation",
  "Tanzania",
  "M M Sports Romance",
  "Star Trek The Next Generation",
  "Academics",
  "Omegaverse",
  "Green",
  "Zambia",
  "Love Inspired Suspense",
  "Esp",
  "Namibia",
  "Bicycles",
  "Helicopters",
  "Amateur Sleuth",
  "Cars",
  "M M Historical Romance",
  "Whodunit",
  "Apple",
  "Nazi Party",
  "Futuristic Romance",
  "Electrical Engineering",
  "Goddess",
  "Cartography",
  "Harlequin Historical",
  "Hqn",
  "Graphic Novels Comics Manga",
  "Canon",
  "Muslimah",
  "Mail Order Brides",
  "Geoffrey Chaucer",
  "Yuri",
  "Nursing",
  "Cryptids",
  "Traditional Chinese Medicine",
  "Read For College",
  "Georgian Romance",
  "Viking Romance",
  "Foster Parents",
  "Field Guides",
  "Ornithology",
  "Multicultural Literature",
  "Human Development",
  "Beer",
  "Soviet Union",
  "Figure Skating",
  "Vaccines",
  "Egyptology",
  "Latin American History",
  "11th Century",
  "Norman",
  "Harlequin Desire",
  "Algorithms",
  "Butch Femme",
  "Libya",
  "Northern Africa",
  "Uganda",
  "Creation Science",
  "Naval Historical Fiction",
  "Harlequin Blaze",
  "Star Trek Deep Space Nine",
  "Silhouette",
  "Gothic Horror",
  "Choose Your Own Adventure",
  "Gamebooks",
  "Gender and Sexuality",
  "Babylon 5",
  "Spiritualism",
  "Global Warming",
  "Fantasy Of Manners",
  "Ivory Coast",
  "Western Africa",
  "Republic Of The Congo",
  "Woodwork",
  "Web",
  "Japanese History",
  "World Of Darkness",
  "Cross Dressing",
  "Fundamentalism",
  "Harlequin Presents",
  "M M Paranormal",
  "Central Africa",
  "Manhwa",
  "Manga Romance",
  "Railways",
  "Anti Intellectualism",
  "Benin",
  "Taxation",
  "Librarianship",
  "Vegetarianism",
  "Harlequin Nocturne",
  "Pseudoscience",
  "Queer Studies",
  "Words",
  "Cultural Heritage",
  "Maps",
  "Gastronomy",
  "M M Young Adult",
  "Back To School",
  "Theosophy",
  "Professors",
  "Tarot",
  "Jewellery",
  "Disability Studies",
  "Erotic Paranormal Romance",
  "Mira",
  "Comics Bd",
  "Wonder Woman",
  "Herbs",
  "Eastern Africa",
  "Christian Contemporary Fiction",
  "Senegal",
  "Cuisine",
  "Battle Of Britain",
  "History Of Medicine",
  "Moroccan",
  "Algebra",
  "Did Not Finish",
  "Low Fantasy",
  "Brewing",
  "Black Literature",
  "Homeschool",
  "Social Change",
  "Star Trek Original Series",
  "Mine",
  "Colouring Books",
  "Aeroplanes",
  "Go",
  "Pre Raphaelite",
  "M M Science Fiction",
  "Goth",
  "Civil War History",
  "Stuart",
  "Library Science",
  "Information Science",
  "Star Trek Voyager",
  "Racing",
  "Led Zeppelin",
  "Belief",
  "Naturopathy",
  "Money Management",
  "Earth Sciences",
  "Classical Music",
  "Food Preservation",
  "M M Mystery",
  "Atlases",
  "Jokes",
  "10th Century",
  "Spanish History",
  "Motorcycling",
  "Civil War Eastern Theater",
  "Aircraft",
  "Traditional Regency",
  "Stand Up",
  "Warriors",
  "Human Resources",
  "London Underground",
  "Far Right",
  "Reportage",
  "Peak Oil",
  "Airships",
  "Guinea",
];
